### PR TITLE
fix: split Microsoft 365/Hotmail functionality

### LINKED ISSUE #1203: Unused Headless feature for Microsoft 365 api
As I know that Microsoft 365 api does not belong to `headless` feature

https://github.com/reacherhq/check-if-email-exists/blob/5d3c49f41ef1369efe2a9e63b24543e281ae0776/core/src/smtp/mod.rs#L20-L21

It lead me to the bug when i try to use the master version after the merge of #1194

```sh
error[E0433]: failed to resolve: use of undeclared crate or module `hotmail`
  --> C:\Users\hoang\.cargo\git\checkouts\check-if-email-exists-c4445d2e2cd9a1bc\5d3c49f\core\src\smtp\mod.rs:73:9
   |
73 |         match hotmail::check_microsoft365_api(to_email, input).await {
   |               ^^^^^^^ use of undeclared crate or module `hotmail`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `check-if-email-exists` due to previous error
warning: build failed, waiting for other jobs to finish...
Internal Error: Command failed: cargo build
```

### PR DESCRIPTION
**Pull request by PsypherPunk**
`hotmail` was previously behind the `headless` feature which, if disabled, breaks the Microsoft 365 API functionality.

refactor these into a `microsoft` module, leaving the `hotmail` module behind the `headless` feature and allowing the Microsoft 365 API to exist separately.

fixes #1203 

---

I've verified that the Microsoft 365 API behaviour is still working in all previously-tested scenarios. 

Someone more familiar with the Hotmail `headless` feature might want to put that through its paces though…?

### CODE REVIEW

File: core/src/smtp/error.rs [hunk 1]
```diff
@@ -45,6 +46,7 @@ pub enum SmtpError {
 	/// Error when verifying a Hotmail email via headless browser.
 	#[cfg(feature = "headless")]
 	HotmailError(HotmailError),
+	Microsoft365Error(Microsoft365Error),
```
Comment (amaurym) [inline core/src/smtp/error.rs:49]:
```suggestion
	/// Error when verifying a Microsoft 365 email via HTTP request.
	Microsoft365Error(Microsoft365Error),
```

**Review by amaurym — COMMENTED** [review]
Code LGTM, i'll do some manual tests before merging

**Review by amaurym — APPROVED** [review]
LGTM
